import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "./ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#0ea5e9" />
        <meta name="application-name" content="Book Swap App" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Book Swap App" />
        <link rel="apple-touch-icon" href="/next.svg" />
        <link rel="canonical" href="https://yourdomain.com/" />
        <meta name="description" content="A platform to swap books." />
        <meta property="og:title" content="Book Swap App" />
        <meta property="og:description" content="A platform to swap books." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://yourdomain.com/" />
        <meta property="og:image" content="/next.svg" />
        <meta property="og:site_name" content="Book Swap App" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Book Swap App" />
        <meta name="twitter:description" content="A platform to swap books." />
        <meta name="twitter:image" content="/next.svg" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
